# Generated by Django 5.2.8 on 2025-11-21 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название клуба')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('town', models.CharField(max_length=100, verbose_name='Город')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('emblem', models.ImageField(blank=True, null=True, upload_to='clubs/', verbose_name='Эмблема')),
                ('founded', models.DateField(verbose_name='Год основания')),
                ('stadium', models.CharField(max_length=255, verbose_name='Стадион')),
                ('match_1', models.IntegerField(default=0, verbose_name='Прошлый матч')),
                ('match_2', models.IntegerField(default=0, verbose_name='Позапрошлый матч')),
                ('match_3', models.IntegerField(default=0, verbose_name='Позапозапрошлый матч')),
                ('match_4', models.IntegerField(default=0, verbose_name='Позапозапозапрошлый матч')),
                ('match_5', models.IntegerField(default=0, verbose_name='Позапозапозапозапрошлый матч')),
                ('next_match', models.IntegerField(default=0, verbose_name='Следующий матч')),
                ('goals', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Забито в среднем')),
                ('possession', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Среднее владение')),
                ('tournaments', models.JSONField(blank=True, default=list, verbose_name='Чемпионаты')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
                'ordering': ['name'],
            },
        ),
    ]
