# Generated by Django 5.2.8 on 2025-11-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='founded',
            field=models.IntegerField(verbose_name='Год основания'),
        ),
    ]
