# Generated by Django 5.2.8 on 2025-11-22 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_club_founded'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='goals_missed',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Пропущено в среднем'),
        ),
        migrations.AlterField(
            model_name='club',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
