# Generated by Django 5.2.8 on 2025-11-22 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_club_goals_missed_alter_club_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=100, verbose_name='Город')),
                ('stadium', models.CharField(max_length=255, verbose_name='Стадион')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('home_goals', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Голы хозяев')),
                ('away_goals', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Голы гостей')),
                ('home_possession', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Владение хозяев (%)')),
                ('away_possession', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Владение гостей (%)')),
                ('home_shots', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Удары хозяев')),
                ('away_shots', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Удары гостей')),
                ('home_shots_on_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Удары в створ хозяев')),
                ('away_shots_on_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Удары в створ гостей')),
                ('home_fouls', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фолы хозяев')),
                ('away_fouls', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фолы гостей')),
                ('home_yellow_cards', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Желтые карточки хозяев')),
                ('away_yellow_cards', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Желтые карточки гостей')),
                ('home_red_cards', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Красные карточки хозяев')),
                ('away_red_cards', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Красные карточки гостей')),
                ('home_corners', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Угловые хозяев')),
                ('away_corners', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Угловые гостей')),
                ('home_offsides', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Офсайды хозяев')),
                ('away_offsides', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Офсайды гостей')),
                ('home_saves', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сейвы хозяев')),
                ('away_saves', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сейвы гостей')),
                ('home_passes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пасы хозяев')),
                ('away_passes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пасы гостей')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('finished', 'Завершен')], default='scheduled', max_length=20, verbose_name='Статус матча')),
                ('tournament', models.CharField(blank=True, max_length=255, null=True, verbose_name='Турнир')),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='main.club', verbose_name='Гости')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='main.club', verbose_name='Хозяева')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['datetime'], name='main_match_datetim_6224f1_idx'), models.Index(fields=['home_club', 'away_club'], name='main_match_home_cl_51f070_idx'), models.Index(fields=['status'], name='main_match_status_4286dc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('home_club', models.F('away_club')), _negated=True), name='prevent_self_match')],
            },
        ),
    ]
