# Generated by Django 5.2.8 on 2025-11-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_club_price_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_corners',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_fouls',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_offsides',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_passes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_yellow_cards',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_corners',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_fouls',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_offsides',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_passes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_yellow_cards',
        ),
    ]
