# Generated by Django 5.2.8 on 2025-12-27 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_match_away_corners_remove_match_away_fouls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=255, unique=True, verbose_name='Название турнира')),
                ('matches_played', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сыграно матчей')),
                ('wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Победы')),
                ('draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ничьи')),
                ('losses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Поражения')),
                ('goals_for', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Забитые голы')),
                ('goals_against', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пропущенные голы')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_results', to='main.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['tournament', '-goals_for'],
                'unique_together': {('tournament', 'club')},
            },
        ),
    ]
