# Generated by Django 5.2.8 on 2025-12-27 03:31

import django.core.validators
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сыграно матчей')),
                ('wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Победы')),
                ('draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ничьи')),
                ('losses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Поражения')),
                ('goals_for', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Забитые голы')),
                ('goals_against', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пропущенные голы')),
            ],
            options={
                'verbose_name': 'Участник турнира',
                'verbose_name_plural': 'Участники турниров',
                'ordering': ['tournament', '-goals_for'],
            },
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['name'], 'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='club',
            name='tournaments',
        ),
        migrations.AddField(
            model_name='tournament',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна проведения'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Tournament.logo_upload_path, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='club',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Club.emblem_upload_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='main.tournament', verbose_name='Турнир'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament'], name='main_match_tournam_cc9ca7_idx'),
        ),
        migrations.AddField(
            model_name='tournamentclub',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to='main.club', verbose_name='Клуб'),
        ),
        migrations.AddField(
            model_name='tournamentclub',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_clubs', to='main.tournament', verbose_name='Турнир'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='clubs',
            field=models.ManyToManyField(related_name='tournaments', through='main.TournamentClub', to='main.club', verbose_name='Клубы-участники'),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='club',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='goals_against',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='goals_for',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='matches_played',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='wins',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentclub',
            unique_together={('tournament', 'club')},
        ),
    ]
