# Generated by Django 5.2.8 on 2026-02-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tournamentclub_alter_tournament_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='emblem_url',
            field=models.URLField(blank=True, verbose_name='Эмблема (URL)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='Логотип (URL)'),
        ),
    ]
