# Generated by Django 5.2.8 on 2026-05-12 00:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_club_emblem_url_tournament_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена билета'),
        ),
        migrations.AddField(
            model_name='match',
            name='seats_available',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доступно мест'),
        ),
    ]
